### PR TITLE
add Dockerfiles and docker-compose.yml

### LINKED ISSUE #83: Prepare deployment and setup test instance
We want the project to be deployed inside a docker-compose with two containers:
- Django/myHPI
- Postgres

The production instance will run inside of HPI (tbd), the test instance should live somewhere in the internet (e.g. heroku)

### PR DESCRIPTION
**Pull request by jeriox**
closes #83 

ToDo

- [x] make postgres and entrypoint working
- [x] think about initial database creation
- [x] add install bootstrap step
- [x] think about process to input environment variables for production

### CODE REVIEW

**Comment by jeriox** [comment]
@frcroth this should enable you to start a working setup on port 80 with docker-compose. I think the question how to set environment variables will depend on the deployment process. Are you going to look into that?

**Comment by frcroth** [comment]
I'm getting `Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/entrypoint.sh": permission denied: unknown` when running `docker-compose up`

**Comment by jeriox** [comment]
> /app/entrypoint.sh": permission denied: unknown
quickly googling the issue reveals that the enytrpoint.sh is not executable. Docker copies the permissions of the source file, which are probably not set in the repo because I am using windows. Do you want to commit the file with chmod +x or should I make the file executable as part of the building process of the container? (see https://stackoverflow.com/questions/38882654/docker-entrypoint-running-bash-script-gets-permission-denied)

**Comment by frcroth** [comment]
Changing permissions of the entrypoint.sh (chmod 777 entrypoint.sh) statically or in the Dockerfile did not resolve the issue.

**Comment by frcroth** [comment]
```
[+] Running 1/0
 ⠿ Container myhpi-postgres-1  Running                                                                                                                              0.0s
Attaching to myhpi-nginx-1, myhpi-postgres-1, myhpi-web-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/entrypoint.sh": permission denied: unknown
```

**Comment by jeriox** [comment]
@frcroth issue should be resolved now

**Review by frcroth — COMMENTED** [review]
After fixing the bootrstrap installation, the docker compose runs through now.

I am then greeted by a flood of the following in the command line:
```
myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
myhpi-web-1       |       [destination] [port]
myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
myhpi-web-1       |       [destination] [port]
myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
myhpi-web-1       |       [destination] [port]
```

Is this intended?

**Comment by jeriox** [comment]
> After fixing the bootrstrap installation, the docker compose runs through now.
> 
> I am then greeted by a flood of the following in the command line:
> 
> ```
> myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
> myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
> myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
> myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
> myhpi-web-1       |       [destination] [port]
> myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
> myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
> myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
> myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
> myhpi-web-1       |       [destination] [port]
> myhpi-web-1       | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
> myhpi-web-1       |       [-m minttl] [-O length] [-P proxy_username] [-p source_port]
> myhpi-web-1       |       [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
> myhpi-web-1       |       [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
> myhpi-web-1       |       [destination] [port]
> ```
> 
> Is this intended?

i can reproduce that with the version that is published in the registry, however if i build the container locally and run it it works just fine. I hate this stuff

**Comment by jeriox** [comment]
@frcroth I think I got it right this time. Could you check it locally? You should be greeted with a`django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable` error message.

That leads to the open checkbox in the PR description. How should be input the environment variables into the container? Currently, a `env_file` is set in the docker_compose.yml which makes it work locally. My proposal would be to include this docker_compose.yml (or a copy when keeping this as template) in the repo of all our compose files and creating an environment file that lives on our VM and is passed into the container with the same mechanism. This allows for the docker image to be publicly availaibe as it does not contain any sensitive information.
Another approach could be to insert the secrets into the image as part of the CI job (via github secrets) and keep the image private afterwards. this would add the complexity of authenticating against the registry

**Review by frcroth — APPROVED** [review]

**Pull request merged**
