### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Paula-Kli**
start of updating dependencies but wagtail itself is still missing

### CODE REVIEW

**Comment by T4rikA** [comment]
I also updated the dependencies in #29, is there a reason why you didn't update wagtail?

**Comment by Paula-Kli** [comment]
> I also updated the dependencies in #29, is there a reason why you didn't update wagtail?

because I did not know that you would update the dependencies in #29 since it is about OIDC and I did not update wagtale since I did not have time yet und would update it as soon as possible

**Comment by jeriox** [comment]
I removed the updates from #29, but you still need to rerun `poetry lock` because we installed an additional dependency

**Comment by frcroth** [comment]
@Paula-Kli Can this be closed?

**Comment by Paula-Kli** [comment]
> @Paula-Kli Can this be closed?

I think so

**Pull request closed without merging**
